name: hierarchical_entity_model_recursively_yielded
description: Henry. My dog's name is Henry.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  petitparser: ^3.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
